---
# roles/postgresql_cluster/tasks

- name: install firewalld
  import_tasks: firewalld.yml

- name: install postgresql 14
  import_tasks: install.yml

- name: generating psql SSH keypair
  import_tasks: keypair.yml

- name: creating repmgrd database and user
  import_tasks: repmgrd_user.yml

- name: backup and configure postgresql
  import_tasks: postgresql.yml

- name: backup and configure repmgrd
  import_tasks: repmgrd.yml

- name: register pg1 as primary
  import_tasks: primary.yml

- name: clone pg2 and resgister as secondary
  import_tasks: standby.yml

- name: enable and start repmgrd service
  import_tasks: repmgrd_svc.yml